#+title: Emacs Major Mode for Majestic Lisp

* Introduction

This is a major mode for editing Majestic Lisp code.

Majestic  Lisp is  a programming  language,  a dialect  of Lisp  built
mostly for educational purposes. It  is inspired by Lisp dialects such
as Bel, Common  Lisp and Clojure. It also draws  some inspiration from
languages such as APL.

* Usage

Right now, ~majestic-mode~ features:

- Syntax highlighting (partially);
- Spawning a Majestic process (still lacks customization);
- Sexp evaluation (with spawned process -- use ~C-c C-c~);
- Marked region evaluation (use ~C-c C-r~).

* Installation

Right now  this package  is too /beta/  to be on  MELPA, so  I recommend
using [[https://github.com/dimitri/el-get][el-get]] to install it from GitHub.

#+begin_src elisp
(el-get-bundle luksamuk/majestic-mode)
(require 'majestic-mode)
#+end_src

If  you want,  you  can update  it  from  time to  time  by using  ~M-x
el-get-update~.

* Syntax examples

Many  code  examples are  on  the  directory  ~examples/~. The  code  is
compatible with the current version  of Majestic Lisp (Version 0.3.0 +
Build ac22fc0-master, nightly, at the time of this writing).

* License

All  code  files in  this  repository  are  provided through  the  MIT
License. See LICENSE for details.

Copyright (c) 2020 Lucas S. Vieira.

